version: 0.2

env:
  shell: /bin/sh
phases:
  install:
    commands:
      - apt-get update
      - apt install -y openjdk-11-jdk
      - apt install -y unzip
      - pip install conan
  pre_build:
    commands:
      - DEV_TOOLS=/home/codebuild-user/devtools
      - ANDROID_HOME=$DEV_TOOLS/Android
      - LOCAL_HOME=/home/codebuild-user/.local/bin
      - PATH=$ANDROID_HOME/build-tools/29.0.3:$LOCAL_HOME:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
      - echo $PATH
      - mkdir -p /home/codebuild-user/devtools/Android/cmdline-tools 
      - cd /home/codebuild-user
      - wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
      - unzip commandlinetools-linux-8512546_latest.zip -d /home/codebuild-user/devtools/Android/cmdline-tools
      - cd /home/codebuild-user/devtools/Android/cmdline-tools
      - mv cmdline-tools latest
      - sdkmanager "platform-tools" "platforms;android-29"
      - sdkmanager "build-tools;29.0.3"
      - yes | sdkmanager --licenses
      - mkdir /home/codebuild-user/Projects
      - cd /home/codebuild-user/Projects
      - git clone https://github.com/alexa/alexa-auto-sdk.git
  build:
    commands:
      - echo $(java --version)
      - echo $(cd /home/codebuild-user/devtools/Android/cmdline-tools/latest/; ls)
      - cd /home/codebuild-user/Projects/alexa-auto-sdk/aacs/android/sample-app
      - ./gradlew assembleLocalRelease
      
    
